{% set name = "kafka-python" %}
{% set version = "1.4.5" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "3100c10601c7a5ddd744186a26148432a4dd0d99f003e90bf6f3bdfd1c9d5406" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python

test:
  imports:
    - kafka
    - kafka.consumer
    - kafka.coordinator
    - kafka.coordinator.assignors
    - kafka.metrics
    - kafka.metrics.stats
    - kafka.partitioner
    - kafka.producer
    - kafka.protocol
    - kafka.serializer
    - kafka.vendor

about:
  home: https://github.com/dpkp/kafka-python
  license_file: LICENSE
  license: Apache 2.0
  license_family: Apache
  summary: 'Pure Python client for Apache Kafka'
  dev_url: https://github.com/dpkp/kafka-python
  doc_url: https://kafka-python.readthedocs.io/en/master/

extra:
  recipe-maintainers:
    - pmlandwehr
