{% set version = "2.2.15" %}

package:
  name: kafka-python
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/k/kafka-python/kafka_python-{{ version }}.tar.gz
  sha256: e0f480a45f3814cb0eb705b8b4f61069e1be61dae0d8c69d0f1f2da33eea1bd5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - kafka
    - kafka.consumer
    - kafka.coordinator
    - kafka.coordinator.assignors
    - kafka.metrics
    - kafka.metrics.stats
    - kafka.partitioner
    - kafka.producer
    - kafka.protocol
    - kafka.serializer
    - kafka.vendor

about:
  home: https://github.com/dpkp/kafka-python
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: Pure Python client for Apache Kafka
  dev_url: https://github.com/dpkp/kafka-python
  doc_url: https://kafka-python.readthedocs.io/en/master/

extra:
  recipe-maintainers:
    - pmlandwehr
    - synapticarbors
