{% set version = "2.1.3" %}

package:
  name: kafka-python
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/k/kafka-python/kafka_python-{{ version }}.tar.gz
  sha256: f312ec01b8b21a9ba1a66d0a5ad0ab5ed732640c1ac886648ef328f6ef4ddb54

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - kafka
    - kafka.consumer
    - kafka.coordinator
    - kafka.coordinator.assignors
    - kafka.metrics
    - kafka.metrics.stats
    - kafka.partitioner
    - kafka.producer
    - kafka.protocol
    - kafka.serializer
    - kafka.vendor

about:
  home: https://github.com/dpkp/kafka-python
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: Pure Python client for Apache Kafka
  dev_url: https://github.com/dpkp/kafka-python
  doc_url: https://kafka-python.readthedocs.io/en/master/

extra:
  recipe-maintainers:
    - pmlandwehr
    - synapticarbors
